### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alimusa970**

### CODE REVIEW

**Comment by camunity** [comment]
@alimusa970 great job on this hw brother. You're missing the last commit "My name is Syed Ali and I'm going to master react!" but everything looks right in the code. Can you add / push that last commit so that I can give you full credit?

**Comment by alimusa970** [comment]
Thank you professor! I will do that right now! 


Sent from Yahoo Mail for iPhone


On Monday, November 2, 2020, 2:40 PM, Cameron Flowers <notifications@github.com> wrote:




@alimusa970 great job on this hw brother. You're missing the last commit "My name is Syed Ali and I'm going to master react!" but everything looks right in the code. Can you add / push that last commit so that I can give you full credit?

**Comment by alimusa970** [comment]
I had just fixed it professor.
    On Monday, November 2, 2020, 02:40:25 PM EST, Cameron Flowers <notifications@github.com> wrote:  
 
 


@alimusa970 great job on this hw brother. You're missing the last commit "My name is Syed Ali and I'm going to master react!" but everything looks right in the code. Can you add / push that last commit so that I can give you full credit?

**Comment by camunity** [comment]
thanks brother!

**Pull request closed without merging**
